<?php

declare(strict_types=1);

namespace Ofx\Enum;

/**
 * ISO 639-1 language codes supported by OFX.
 *
 * Used for specifying the language of text content in OFX messages.
 */
enum Language: string
{
    case AAR = 'AAR'; // Afar
    case ABK = 'ABK'; // Abkhazian
    case ACE = 'ACE'; // Achinese
    case ACH = 'ACH'; // Acoli
    case ADA = 'ADA'; // Adangme
    case AFA = 'AFA'; // Afro-Asiatic (Other)
    case AFH = 'AFH'; // Afrihili
    case AFR = 'AFR'; // Afrikaans
    case AKA = 'AKA'; // Akan
    case AKK = 'AKK'; // Akkadian
    case ALB = 'ALB'; // Albanian
    case ALE = 'ALE'; // Aleut
    case ALG = 'ALG'; // Algonquian languages
    case AMH = 'AMH'; // Amharic
    case ANG = 'ANG'; // English, Old (ca.450-1100)
    case APA = 'APA'; // Apache languages
    case ARA = 'ARA'; // Arabic
    case ARC = 'ARC'; // Aramaic
    case ARM = 'ARM'; // Armenian
    case ARN = 'ARN'; // Araucanian
    case ARP = 'ARP'; // Arapaho
    case ART = 'ART'; // Artificial (Other)
    case ARW = 'ARW'; // Arawak
    case ASM = 'ASM'; // Assamese
    case ATH = 'ATH'; // Athapascan languages
    case AUS = 'AUS'; // Australian languages
    case AVA = 'AVA'; // Avaric
    case AVE = 'AVE'; // Avestan
    case AWA = 'AWA'; // Awadhi
    case AYM = 'AYM'; // Aymara
    case AZE = 'AZE'; // Azerbaijani
    case BAD = 'BAD'; // Banda
    case BAI = 'BAI'; // Bamileke languages
    case BAK = 'BAK'; // Bashkir
    case BAL = 'BAL'; // Baluchi
    case BAM = 'BAM'; // Bambara
    case BAN = 'BAN'; // Balinese
    case BAQ = 'BAQ'; // Basque
    case BAS = 'BAS'; // Basa
    case BAT = 'BAT'; // Baltic (Other)
    case BEJ = 'BEJ'; // Beja
    case BEL = 'BEL'; // Belarusian
    case BEM = 'BEM'; // Bemba
    case BEN = 'BEN'; // Bengali
    case BER = 'BER'; // Berber (Other)
    case BHO = 'BHO'; // Bhojpuri
    case BIH = 'BIH'; // Bihari
    case BIK = 'BIK'; // Bikol
    case BIN = 'BIN'; // Bini
    case BIS = 'BIS'; // Bislama
    case BLA = 'BLA'; // Siksika
    case BNT = 'BNT'; // Bantu (Other)
    case BOS = 'BOS'; // Bosnian
    case BRA = 'BRA'; // Braj
    case BRE = 'BRE'; // Breton
    case BTK = 'BTK'; // Batak (Indonesia)
    case BUA = 'BUA'; // Buriat
    case BUG = 'BUG'; // Buginese
    case BUL = 'BUL'; // Bulgarian
    case BUR = 'BUR'; // Burmese
    case CAD = 'CAD'; // Caddo
    case CAI = 'CAI'; // Central American Indian (Other)
    case CAR = 'CAR'; // Carib
    case CAT = 'CAT'; // Catalan
    case CAU = 'CAU'; // Caucasian (Other)
    case CEB = 'CEB'; // Cebuano
    case CEL = 'CEL'; // Celtic (Other)
    case CHA = 'CHA'; // Chamorro
    case CHB = 'CHB'; // Chibcha
    case CHE = 'CHE'; // Chechen
    case CHG = 'CHG'; // Chagatai
    case CHI = 'CHI'; // Chinese
    case CHK = 'CHK'; // Chuukese
    case CHM = 'CHM'; // Mari
    case CHN = 'CHN'; // Chinook jargon
    case CHO = 'CHO'; // Choctaw
    case CHP = 'CHP'; // Chipewyan
    case CHR = 'CHR'; // Cherokee
    case CHU = 'CHU'; // Church Slavic
    case CHV = 'CHV'; // Chuvash
    case CHY = 'CHY'; // Cheyenne
    case CMC = 'CMC'; // Chamic languages
    case COP = 'COP'; // Coptic
    case COR = 'COR'; // Cornish
    case COS = 'COS'; // Corsican
    case CPE = 'CPE'; // Creoles and pidgins, English based (Other)
    case CPF = 'CPF'; // Creoles and pidgins, French-based (Other)
    case CPP = 'CPP'; // Creoles and pidgins, Portuguese-based (Other)
    case CRE = 'CRE'; // Cree
    case CRP = 'CRP'; // Creoles and pidgins (Other)
    case CUS = 'CUS'; // Cushitic (Other)
    case CZE = 'CZE'; // Czech
    case DAK = 'DAK'; // Dakota
    case DAN = 'DAN'; // Danish
    case DAR = 'DAR'; // Dargwa
    case DAY = 'DAY'; // Dayak
    case DEL = 'DEL'; // Delaware
    case DEN = 'DEN'; // Slave (Athapascan)
    case DGR = 'DGR'; // Dogrib
    case DIN = 'DIN'; // Dinka
    case DIV = 'DIV'; // Divehi
    case DOI = 'DOI'; // Dogri
    case DRA = 'DRA'; // Dravidian (Other)
    case DUA = 'DUA'; // Duala
    case DUM = 'DUM'; // Dutch, Middle (ca. 1050-1350)
    case DUT = 'DUT'; // Dutch
    case DYU = 'DYU'; // Dyula
    case DZO = 'DZO'; // Dzongkha
    case EFI = 'EFI'; // Efik
    case EGY = 'EGY'; // Egyptian (Ancient)
    case EKA = 'EKA'; // Ekajuk
    case ELX = 'ELX'; // Elamite
    case ENG = 'ENG'; // English
    case ENM = 'ENM'; // English, Middle (1100-1500)
    case EPO = 'EPO'; // Esperanto
    case EST = 'EST'; // Estonian
    case EWE = 'EWE'; // Ewe
    case EWO = 'EWO'; // Ewondo
    case FAN = 'FAN'; // Fang
    case FAO = 'FAO'; // Faroese
    case FAT = 'FAT'; // Fanti
    case FIJ = 'FIJ'; // Fijian
    case FIN = 'FIN'; // Finnish
    case FIU = 'FIU'; // Finno-Ugrian (Other)
    case FON = 'FON'; // Fon
    case FRE = 'FRE'; // French
    case FRM = 'FRM'; // French, Middle (ca. 1400-1600)
    case FRO = 'FRO'; // French, Old (842-ca. 1400)
    case FRY = 'FRY'; // Frisian
    case FUL = 'FUL'; // Fulah
    case FUR = 'FUR'; // Friulian
    case GAA = 'GAA'; // Ga
    case GAY = 'GAY'; // Gayo
    case GBA = 'GBA'; // Gbaya
    case GEM = 'GEM'; // Germanic (Other)
    case GEO = 'GEO'; // Georgian
    case GER = 'GER'; // German
    case GEZ = 'GEZ'; // Geez
    case GIL = 'GIL'; // Gilbertese
    case GLA = 'GLA'; // Gaelic (Scots)
    case GLE = 'GLE'; // Irish
    case GLG = 'GLG'; // Gallegan
    case GLV = 'GLV'; // Manx
    case GMH = 'GMH'; // German, Middle High (ca. 1050-1500)
    case GOH = 'GOH'; // German, Old High (ca. 750-1050)
    case GON = 'GON'; // Gondi
    case GOR = 'GOR'; // Gorontalo
    case GOT = 'GOT'; // Gothic
    case GRB = 'GRB'; // Grebo
    case GRC = 'GRC'; // Greek, Ancient (to 1453)
    case GRE = 'GRE'; // Greek, Modern (1453-)
    case GRN = 'GRN'; // Guarani
    case GUJ = 'GUJ'; // Gujarati
    case GWI = 'GWI'; // Gwich in
    case HAI = 'HAI'; // Haida
    case HAU = 'HAU'; // Hausa
    case HAW = 'HAW'; // Hawaiian
    case HEB = 'HEB'; // Hebrew
    case HER = 'HER'; // Herero
    case HIL = 'HIL'; // Hiligaynon
    case HIM = 'HIM'; // Himachali
    case HIN = 'HIN'; // Hindi
    case HIT = 'HIT'; // Hittite
    case HMN = 'HMN'; // Hmong
    case HMO = 'HMO'; // Hiri Motu
    case HUN = 'HUN'; // Hungarian
    case HUP = 'HUP'; // Hupa
    case IBA = 'IBA'; // Iban
    case IBO = 'IBO'; // Igbo
    case ICE = 'ICE'; // Icelandic
    case IDO = 'IDO'; // Ido
    case III = 'III'; // Sichuan Yi
    case IJO = 'IJO'; // Ijo
    case IKU = 'IKU'; // Inuktitut
    case ILE = 'ILE'; // Interlingue
    case ILO = 'ILO'; // Iloko
    case INA = 'INA'; // Interlingua
    case INC = 'INC'; // Indic (Other)
    case IND = 'IND'; // Indonesian
    case INE = 'INE'; // Indo-European (Other)
    case INH = 'INH'; // Ingush
    case IPK = 'IPK'; // Inupiaq
    case IRA = 'IRA'; // Iranian (Other)
    case IRO = 'IRO'; // Iroquoian languages
    case ITA = 'ITA'; // Italian
    case JAV = 'JAV'; // Javanese
    case JPN = 'JPN'; // Japanese
    case JPR = 'JPR'; // Judeo-Persian
    case JRB = 'JRB'; // Judeo-Arabic
    case KAA = 'KAA'; // Kara-Kalpak
    case KAB = 'KAB'; // Kabyle
    case KAC = 'KAC'; // Kachin
    case KAL = 'KAL'; // Kalaallisut
    case KAM = 'KAM'; // Kamba
    case KAN = 'KAN'; // Kannada
    case KAR = 'KAR'; // Karen
    case KAS = 'KAS'; // Kashmiri
    case KAU = 'KAU'; // Kanuri
    case KAW = 'KAW'; // Kawi
    case KAZ = 'KAZ'; // Kazakh
    case KBD = 'KBD'; // Kabardian
    case KHA = 'KHA'; // Khasi
    case KHI = 'KHI'; // Khoisan (Other)
    case KHM = 'KHM'; // Khmer
    case KHO = 'KHO'; // Khotanese
    case KIK = 'KIK'; // Kikuyu
    case KIN = 'KIN'; // Kinyarwanda
    case KIR = 'KIR'; // Kirghiz
    case KMB = 'KMB'; // Kimbundu
    case KOK = 'KOK'; // Konkani
    case KOM = 'KOM'; // Komi
    case KON = 'KON'; // Kongo
    case KOR = 'KOR'; // Korean
    case KOS = 'KOS'; // Kosraean
    case KPE = 'KPE'; // Kpelle
    case KRO = 'KRO'; // Kru
    case KRU = 'KRU'; // Kurukh
    case KUA = 'KUA'; // Kuanyama
    case KUM = 'KUM'; // Kumyk
    case KUR = 'KUR'; // Kurdish
    case KUT = 'KUT'; // Kutenai
    case LAD = 'LAD'; // Ladino
    case LAH = 'LAH'; // Lahnda
    case LAM = 'LAM'; // Lamba
    case LAO = 'LAO'; // Lao
    case LAT = 'LAT'; // Latin
    case LAV = 'LAV'; // Latvian
    case LEZ = 'LEZ'; // Lezghian
    case LIM = 'LIM'; // Limburgan
    case LIN = 'LIN'; // Lingala
    case LIT = 'LIT'; // Lithuanian
    case LOL = 'LOL'; // Mongo
    case LOZ = 'LOZ'; // Lozi
    case LTZ = 'LTZ'; // Luxembourgish
    case LUA = 'LUA'; // Luba-Lulua
    case LUB = 'LUB'; // Luba-Katanga
    case LUG = 'LUG'; // Ganda
    case LUI = 'LUI'; // Luiseno
    case LUN = 'LUN'; // Lunda
    case LUO = 'LUO'; // Luo (Kenya and Tanzania)
    case LUS = 'LUS'; // Lushai
    case MAC = 'MAC'; // Macedonian
    case MAD = 'MAD'; // Madurese
    case MAG = 'MAG'; // Magahi
    case MAH = 'MAH'; // Marshallese
    case MAI = 'MAI'; // Maithili
    case MAK = 'MAK'; // Makasar
    case MAL = 'MAL'; // Malayalam
    case MAN = 'MAN'; // Mandingo
    case MAO = 'MAO'; // Maori
    case MAP = 'MAP'; // Austronesian (Other)
    case MAR = 'MAR'; // Marathi
    case MAS = 'MAS'; // Masai
    case MAY = 'MAY'; // Malay
    case MDR = 'MDR'; // Mandar
    case MEN = 'MEN'; // Mende
    case MGA = 'MGA'; // Irish, Middle (900-1200)
    case MIC = 'MIC'; // Micmac
    case MIN = 'MIN'; // Minangkabau
    case MIS = 'MIS'; // Miscellaneous languages
    case MKH = 'MKH'; // Mon-Khmer (Other)
    case MLG = 'MLG'; // Malagasy
    case MLT = 'MLT'; // Maltese
    case MNC = 'MNC'; // Manchu
    case MNI = 'MNI'; // Manipuri
    case MNO = 'MNO'; // Manobo languages
    case MOH = 'MOH'; // Mohawk
    case MOL = 'MOL'; // Moldavian
    case MON = 'MON'; // Mongolian
    case MOS = 'MOS'; // Mossi
    case MUL = 'MUL'; // Multiple languages
    case MUN = 'MUN'; // Munda languages
    case MUS = 'MUS'; // Creek
    case MWR = 'MWR'; // Marwari
    case MYN = 'MYN'; // Mayan languages
    case NAH = 'NAH'; // Nahuatl
    case NAI = 'NAI'; // North American Indian
    case NAP = 'NAP'; // Neapolitan
    case NAU = 'NAU'; // Nauru
    case NAV = 'NAV'; // Navajo
    case NBL = 'NBL'; // Ndebele, South
    case NDE = 'NDE'; // Ndebele, North
    case NDO = 'NDO'; // Ndonga
    case NDS = 'NDS'; // Low German
    case NEP = 'NEP'; // Nepali
    case NEW = 'NEW'; // Newari
    case NIA = 'NIA'; // Nias
    case NIC = 'NIC'; // Niger-Kordofanian (Other)
    case NIU = 'NIU'; // Niuean
    case NNO = 'NNO'; // Norwegian Nynorsk
    case NOB = 'NOB'; // Norwegian Bokmal
    case NON = 'NON'; // Norse, Old
    case NOR = 'NOR'; // Norwegian
    case NSO = 'NSO'; // Northern Sotho
    case NUB = 'NUB'; // Nubian languages
    case NYA = 'NYA'; // Chichewa
    case NYM = 'NYM'; // Nyamwezi
    case NYN = 'NYN'; // Nyankole
    case NYO = 'NYO'; // Nyoro
    case NZI = 'NZI'; // Nzima
    case OCI = 'OCI'; // Occitan (post 1500)
    case OJI = 'OJI'; // Ojibwa
    case ORI = 'ORI'; // Oriya
    case ORM = 'ORM'; // Oromo
    case OSA = 'OSA'; // Osage
    case OSS = 'OSS'; // Ossetian
    case OTA = 'OTA'; // Turkish, Ottoman (1500-1928)
    case OTO = 'OTO'; // Otomian languages
    case PAA = 'PAA'; // Papuan (Other)
    case PAG = 'PAG'; // Pangasinan
    case PAL = 'PAL'; // Pahlavi
    case PAM = 'PAM'; // Pampanga
    case PAN = 'PAN'; // Panjabi
    case PAP = 'PAP'; // Papiamento
    case PAU = 'PAU'; // Palauan
    case PEO = 'PEO'; // Persian, Old (ca. 600-400 B.C.)
    case PER = 'PER'; // Persian
    case PHI = 'PHI'; // Philippine (Other)
    case PHN = 'PHN'; // Phoenician
    case PLI = 'PLI'; // Pali
    case POL = 'POL'; // Polish
    case PON = 'PON'; // Pohnpeian
    case POR = 'POR'; // Portuguese
    case PRA = 'PRA'; // Prakrit languages
    case PRO = 'PRO'; // Provencal, Old (to 1500)
    case PUS = 'PUS'; // Pushto
    case QUE = 'QUE'; // Quechua
    case RAJ = 'RAJ'; // Rajasthani
    case RAP = 'RAP'; // Rapanui
    case RAR = 'RAR'; // Rarotongan
    case ROA = 'ROA'; // Romance (Other)
    case ROH = 'ROH'; // Raeto-Romance
    case ROM = 'ROM'; // Romany
    case RUM = 'RUM'; // Romanian
    case RUN = 'RUN'; // Rundi
    case RUS = 'RUS'; // Russian
    case SAD = 'SAD'; // Sandawe
    case SAG = 'SAG'; // Sango
    case SAH = 'SAH'; // Yakut
    case SAI = 'SAI'; // South American Indian (Other)
    case SAL = 'SAL'; // Salishan languages
    case SAM = 'SAM'; // Samaritan Aramaic
    case SAN = 'SAN'; // Sanskrit
    case SAS = 'SAS'; // Sasak
    case SAT = 'SAT'; // Santali
    case SCC = 'SCC'; // Serbian
    case SCO = 'SCO'; // Scots
    case SCR = 'SCR'; // Croatian
    case SEL = 'SEL'; // Selkup
    case SEM = 'SEM'; // Semitic (Other)
    case SGA = 'SGA'; // Irish, Old (to 900)
    case SGN = 'SGN'; // Sign Languages
    case SHN = 'SHN'; // Shan
    case SID = 'SID'; // Sidamo
    case SIN = 'SIN'; // Sinhalese
    case SIO = 'SIO'; // Siouan languages
    case SIT = 'SIT'; // Sino-Tibetan (Other)
    case SLA = 'SLA'; // Slavic (Other)
    case SLO = 'SLO'; // Slovak
    case SLV = 'SLV'; // Slovenian
    case SMA = 'SMA'; // Southern Sami
    case SME = 'SME'; // Northern Sami
    case SMI = 'SMI'; // Sami languages (Other)
    case SMJ = 'SMJ'; // Lule Sami
    case SMN = 'SMN'; // Inari Sami
    case SMO = 'SMO'; // Samoan
    case SMS = 'SMS'; // Skolt Sami
    case SNA = 'SNA'; // Shona
    case SND = 'SND'; // Sindhi
    case SNK = 'SNK'; // Soninke
    case SOG = 'SOG'; // Sogdian
    case SOM = 'SOM'; // Somali
    case SON = 'SON'; // Songhai
    case SOT = 'SOT'; // Sotho, Southern
    case SPA = 'SPA'; // Spanish
    case SRD = 'SRD'; // Sardinian
    case SRR = 'SRR'; // Serer
    case SSA = 'SSA'; // Nilo-Saharan (Other)
    case SSW = 'SSW'; // Swati
    case SUK = 'SUK'; // Sukuma
    case SUN = 'SUN'; // Sundanese
    case SUS = 'SUS'; // Susu
    case SUX = 'SUX'; // Sumerian
    case SWA = 'SWA'; // Swahili
    case SWE = 'SWE'; // Swedish
    case SYR = 'SYR'; // Syriac
    case TAH = 'TAH'; // Tahitian
    case TAI = 'TAI'; // Tai (Other)
    case TAM = 'TAM'; // Tamil
    case TAT = 'TAT'; // Tatar
    case TEL = 'TEL'; // Telugu
    case TEM = 'TEM'; // Timne
    case TER = 'TER'; // Tereno
    case TET = 'TET'; // Tetum
    case TGK = 'TGK'; // Tajik
    case TGL = 'TGL'; // Tagalog
    case THA = 'THA'; // Thai
    case TIB = 'TIB'; // Tibetan
    case TIG = 'TIG'; // Tigre
    case TIR = 'TIR'; // Tigrinya
    case TIV = 'TIV'; // Tiv
    case TKL = 'TKL'; // Tokelau
    case TLI = 'TLI'; // Tlingit
    case TMH = 'TMH'; // Tamashek
    case TOG = 'TOG'; // Tonga (Nyasa)
    case TON = 'TON'; // Tonga (Tonga Islands)
    case TPI = 'TPI'; // Tok Pisin
    case TSI = 'TSI'; // Tsimshian
    case TSN = 'TSN'; // Tswana
    case TSO = 'TSO'; // Tsonga
    case TUK = 'TUK'; // Turkmen
    case TUM = 'TUM'; // Tumbuka
    case TUP = 'TUP'; // Tupi languages
    case TUR = 'TUR'; // Turkish
    case TUT = 'TUT'; // Altaic (Other)
    case TVL = 'TVL'; // Tuvalu
    case TWI = 'TWI'; // Twi
    case TYV = 'TYV'; // Tuvinian
    case UGA = 'UGA'; // Ugaritic
    case UIG = 'UIG'; // Uighur
    case UKR = 'UKR'; // Ukrainian
    case UMB = 'UMB'; // Umbundu
    case UND = 'UND'; // Undetermined
    case URD = 'URD'; // Urdu
    case UZB = 'UZB'; // Uzbek
    case VAI = 'VAI'; // Vai
    case VEN = 'VEN'; // Venda
    case VIE = 'VIE'; // Vietnamese
    case VOL = 'VOL'; // Volapuk
    case VOT = 'VOT'; // Votic
    case WAK = 'WAK'; // Wakashan languages
    case WAL = 'WAL'; // Walamo
    case WAR = 'WAR'; // Waray
    case WAS = 'WAS'; // Washo
    case WEL = 'WEL'; // Welsh
    case WEN = 'WEN'; // Sorbian languages
    case WLN = 'WLN'; // Walloon
    case WOL = 'WOL'; // Wolof
    case XHO = 'XHO'; // Xhosa
    case YAO = 'YAO'; // Yao
    case YAP = 'YAP'; // Yapese
    case YID = 'YID'; // Yiddish
    case YOR = 'YOR'; // Yoruba
    case YPK = 'YPK'; // Yupik languages
    case ZAP = 'ZAP'; // Zapotec
    case ZEN = 'ZEN'; // Zenaga
    case ZHA = 'ZHA'; // Zhuang
    case ZND = 'ZND'; // Zande
    case ZUL = 'ZUL'; // Zulu
    case ZUN = 'ZUN'; // Zuni
}
